name: CI

on:
  push:
    branches: [ "main", "ostree" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the image
        run: ./build ostree
